### ISSUE TITLE
Can the code run in CPU mode?

### ISSUE THREAD

**Issue by yaseryacoob** [yulequan/EC-Net#1]
Installed Tensorflow in CPU mode, can and how would your code be modified for CPU mode?
thanks

**Comment by yulequan** [comment]
I do not test it in the CPU mode. But the change should be straightforward.  Maybe you can try set CUDA_VISIBLE_DEVICES=""

**Comment by yaseryacoob** [comment]
I am in the tf_ops stage and the .sh files seem to require cuda?

Thanks

YY

**Comment by yulequan** [comment]
Oh, I see. The tf_ops do not have the cpu version and you must run it in GPU.
