### ISSUE TITLE
Code for generating scanned point cloud from shapenet object

### ISSUE THREAD

**Issue by xuelin-chen** [yulequan/EC-Net#3]
Dear @yulequan , thanks for sharing the code. I am wondering if you can share the code of generating point clouds from ShapeNet models as described in the paper? Thank you. :)

**Comment by yulequan** [comment]
Hi,  we will release the simulation code several days later.

**Comment by xuelin-chen** [comment]
Thanks for the reply and looking forward to it. :)

**Comment by yulequan** [comment]
Hi @ChenXuelinCXL, I have uploaded the virtual scan code. This code is not very clean and you need to carefully read it.

**Comment by xuelin-chen** [comment]
@yulequan Thanks a lot!
