### ISSUE TITLE
 I got errors when import pygraph.algorithms 

### ISSUE THREAD

**Issue by Asher-1** [yulequan/EC-Net#6]
python main.py --phase test --log_dir ../model/pretrain
Traceback (most recent call last):
  File "main.py", line 18, in <module>
    from GKNN import GKNN
  File "/home/yons/develop/AI/Robots/3d_modeling/EC-Net/code/GKNN.py", line 6, in <module>
    import pygraph.algorithms
ImportError: No module named algorithms

**Comment by yulequan** [comment]
Hi, it seems that you do not successfully install the pygraph library.

**Comment by GaryW666** [comment]
> python main.py --phase test --log_dir ../model/pretrain Traceback (most recent call last): File "main.py", line 18, in from GKNN import GKNN File "/home/yons/develop/AI/Robots/3d_modeling/EC-Net/code/GKNN.py", line 6, in import pygraph.algorithms ImportError: No module named algorithms

hello，have you solved this error？ I have got the save problem with you.
